# pull official base image
FROM node:alpine

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /app

# install app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install react-scripts -g --silent

# add app
COPY ./src /app/src
COPY ./public /app/public

EXPOSE 3000

# start app
CMD ["npm", "start"]