name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
    - 
      name: Set GitHub short hash
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - 
      name: Print GitHub short hash
      run: echo "Short hash=$GITHUB_SHA_SHORT"

    - 
      uses: actions/setup-node@v1
      name: Node.js
      with:
        node-version: 16
    - 
      name: yarn build
      run: |
        cd ${GITHUB_WORKSPACE}/example.api
        ls
        yarn
        yarn build
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Set Docker username
      run: echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./example.api/
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/example-api:${{ env.GITHUB_SHA_SHORT }}