name: ci

on:
  push:
    branches:
      - 'main'
env:
  API_SRC_FOLDER: "example.api"
  API_APP_NAME: "example-api"
  API_IMAGE_FILE: infra/manifests/lib/api.image.txt
  WEB_SRC_FOLDER: "example.website"
  WEB_APP_NAME: "example-website"
  WEB_IMAGE_FILE: infra/manifests/lib/website.image.txt

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      sha_short: ${{ steps.set_sha.outputs.GITHUB_SHA_SHORT }}
    steps:
    - uses: actions/checkout@v3
    - id: set_sha
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: WEB - Build
      run: |
        cd ${GITHUB_WORKSPACE}/$WEB_SRC_FOLDER
        ls
        npm install
        npm install react-scripts

    - name: API - Build
      run: |
        cd ${GITHUB_WORKSPACE}/$API_SRC_FOLDER
        ls
        yarn
        yarn build
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: API - Build and push 
      uses: docker/build-push-action@v3
      with:
        context: ./${{ env.API_SRC_FOLDER }}/
        push: true
        tags: "${{ env.DOCKERHUB_USERNAME }}/${{ env.API_APP_NAME }}:${{ steps.set_sha.outputs.GITHUB_SHA_SHORT }}"

    - name: API - Write build image to file
      run: | 
        : > ${GITHUB_WORKSPACE}/${{ env.API_IMAGE_FILE }}
        echo ${{ env.DOCKERHUB_USERNAME }}/${{ env.API_APP_NAME }}:${{ steps.set_sha.outputs.GITHUB_SHA_SHORT }} | xargs | tr -d '\n' > ${GITHUB_WORKSPACE}/${{ env.API_IMAGE_FILE }}
        cat ${GITHUB_WORKSPACE}/${{ env.API_IMAGE_FILE }}

    - name: Website - Build and push 
      uses: docker/build-push-action@v3
      with:
        context: ./${{ env.WEB_SRC_FOLDER }}/
        push: true
        tags: "${{ env.DOCKERHUB_USERNAME }}/${{ env.WEB_APP_NAME }}:${{ steps.set_sha.outputs.GITHUB_SHA_SHORT }}"

    - name: Website - Write build image to file
      run: | 
        : > ${GITHUB_WORKSPACE}/${{ env.WEB_IMAGE_FILE }}
        echo ${{ env.DOCKERHUB_USERNAME }}/${{ env.WEB_APP_NAME }}:${{ steps.set_sha.outputs.GITHUB_SHA_SHORT }} | xargs | tr -d '\n' > ${GITHUB_WORKSPACE}/${{ env.WEB_IMAGE_FILE }}
        cat ${GITHUB_WORKSPACE}/${{ env.WEB_IMAGE_FILE }}

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        commit_message: Version updated to ${{ steps.set_sha.outputs.GITHUB_SHA_SHORT }}