name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$calculatedSha"

    - name: Confirm git commit SHA output
      run: echo ${{ steps.vars.outputs.short_sha }}

      # - uses: actions/checkout@v2
      # - name: Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16
      # - run: npm install -g yarn
      # - name: yarn install, build and test
      #   run: |
      #     cd ${GITHUB_WORKSPACE}/example.api
      #     ls
      #     yarn
      #     yarn build
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./example.api/
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/example-api:${{ steps.vars.outputs.sha_short }}